blog/urls.py
from django.urls import path
from .views import (
    PostsListView,
    AboutView,
    ContactViev,
    DetailView,
    SearchView,
    CreatePostView,
    UpdatePostView,
    DeletePostView,
CommentCreateView,
    CategoryPostView,
    LikePostView,
    CommentCreateView,
    CategoryPostView,
    LikePostView,

CommentCreateView
    )

app_name = 'blog'

urlpatterns = [
    path('', PostsListView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactViev.as_view(), name='contact'),
    path('detail/<int:pk>/', DetailView.as_view(), name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('post/new/', CreatePostView.as_view(), name='post_create'),
    path('post/<int:pk>/edit', UpdatePostView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', DeletePostView.as_view(), name='post_delete'),
    path('post/comment/', CommentCreateView.as_view(), name='post_comment'),
    path('categories/<int:pk>/posts', CategoryPostView.as_view(), name='category_posts'),
    path('like-post/<int:pk>/', LikePostView.as_view(), name='like-post'),
    path('post/comment/', CommentCreateView.as_view(), name='comment'),
    # path('post/comment/', CommentCreateView.as_view(), name='post_comment'),
    # path('categories/<int:pk>/posts', CategoryPostView.as_view(), name='category_posts'),
    # path('like-post/<int:pk>/', LikePostView.as_view(), name='like-post'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('user/', include('user.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, related_name='posts')
    short_desc = models.CharField(max_length=300)
    content = RichTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)
    views = models.PositiveBigIntegerField(default=0)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'


class Message(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.CharField(max_length=300)
    is_read = models.BooleanField(default=False)
    sended_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-sended_at']
        verbose_name = 'message'
        verbose_name_plural = 'messages'

    def __str__(self):
        return f"{self.message[:15]} from {self.name}"

blog/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post, Comment

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'categories', 'short_desc', 'content', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'categories': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'short_desc': forms.TextInput(attrs={'class': 'form-control'}),
            'content': CKEditorWidget(),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
from django.shortcuts import render,  redirect, get_object_or_404
from django.views import View
from .models import Category, Post, Comment
from datetime import datetime
from django.db.models import Q
from django.core.paginator import Paginator
from .forms import PostCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

def get_today():
    return datetime.date(datetime.today())

def get_categories():
    return Category.objects.all()

def get_related_post():
    posts = Post.objects.all()
    return posts

def get_latest_post():
    return Post.objects.all().first()


# Create your views here.

class PostsListView(View):
    def get(self, request):
        posts_list = Post.objects.all()
        paginator = Paginator(posts_list, 4)
        page_number = request.GET.get('page', 1)  
        posts = paginator.get_page(page_number)

        context = {
            'categories': get_categories(),
            'today': get_today(),
            'posts': posts
        }
        return render(request, 'blog/index.html', context)
    

class CreatePostView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'blog:post_create'

    def get(self, request):
        return self.render_form(PostCreateForm())

    def post(self, request):
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:index')
        return self.render_form(form)

    def render_form(self, form):
        return render(self.request, 'blog/post_create.html', {'form': form})


class UpdatePostView(UserPassesTestMixin, LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'blog:post_update'

    def get_object(self, pk):
        return get_object_or_404(Post, id=pk)

    def get(self, request, pk):
        post = self.get_object(pk)
        form = PostCreateForm(instance=post)
        return render(request, 'blog/post_update.html', {'form': form})

    def post(self, request, pk):
        post = self.get_object(pk)
        form = PostCreateForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save()
            return redirect('blog:detail', pk=pk)

        return render(request, 'blog/post_update.html', {'form': form})

    def test_func(self):
        post = self.get_object(self.kwargs['pk'])
        return post.author == self.request.user


class DeletePostView(UserPassesTestMixin, LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'blog:post_delete'

    def get_object(self, pk):
        return get_object_or_404(Post, id=pk)

    def test_func(self):
        post = self.get_object(self.kwargs['pk'])
        return post.author == self.request.user

    def get(self, request, pk):
        post = self.get_object(pk)
        return render(request, 'blog/post_delete.html', {'post': post})

    def post(self, request, pk):
        post = self.get_object(pk)
        post.delete()
        return redirect('blog:index')
    


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        message = request.POST.get('message')
        post_id = request.POST.get('post_id')

        if not message.strip():
            return JsonResponse({'error': "Izoh bo'sh bo'lmasligi kerak!"}, status=400)

        post = get_object_or_404(Post, id=post_id)

        comment = Comment.objects.create(
            post=post,
            author=request.user,
            content=message
        )

        return JsonResponse({
            'message': 'Comment added successfully!',
            'comment': {
                'author': f'{comment.author.first_name} {comment.author.last_name}',
                'content': comment.content,
                'created_at': comment.created_at.strftime('%Y-%m-%d')
            }
        })


class CategoryPostView(View):
    def get(self, request, pk):
        ctg = get_object_or_404(Category, id=pk)
        posts = Post.objects.filter(categories=ctg)
        return render(request, 'blog/category_post.html', {'posts': posts})


class LikePostView(LoginRequiredMixin, View):
    def post(self, request, pk):
        post = get_object_or_404(Post, id=pk)

        if request.user in post.likes.all():
            post.likes.remove(request.user)
            liked = False
        else:
            post.likes.add(request.user)
            liked = True

        return JsonResponse({
            "status": "liked" if liked else "unliked",
            "like_count": post.likes.count()
        })

class AboutView(View):
    def get(self, request):
        return render(request, 'blog/about.html')


class ContactViev(View):
    def get(self, request):
        return render(request, 'blog/contact.html')
    

class DetailView(View):
    def get(self, request, pk):
        print(get_latest_post())
        post_ = Post.objects.get(pk=pk)

        related_posts = Post.objects.filter(categories__in=post_.categories.all()).exclude(id=post_.id).distinct()

        post_.views += 1
        post_.save()
        context = {
            'post_': post_,
            'latest_post': get_latest_post(),
            'related_posts': related_posts,
            'categories': get_categories(),
            'today': get_today(),
            'comments': post_.comments.all()
        }

        return render(request, 'blog/detail.html', context)
    
    def post(self, request, pk):
        query = request.GET.get('query')
        posts = Post.objects.filter(title_icontains=query) if query else Post.objects.all()
        post_ = Post.objects.get(pk=pk)

        context = {
            'post_': post_,
            'posts': posts,
            'latest_post': get_latest_post(),
            'today': get_today(),
            'related_posts': get_related_post(),
            'categories': get_categories(),

        }

        # content = request.GET.get('message')
        # if content:
        #     comment = Comment.objects.create(content=content)
        #     comment.save()
            

        return render(request, 'blog/detail.html', context)


class SearchView(View):
    def get(self, request):
        query = request.GET.get('query', '')
        results = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))
        return render(request, 'search.html', {'query': query, 'results': results})

templates/blog/about.html
{% extends 'blog/base.html' %}
{% block main %}
{% load static %}
    <div class="row tm-row tm-mb-40">
        <div class="col-12">                    
            <div class="mb-4">
                <h2 class="pt-2 tm-mb-40 tm-color-primary tm-post-title">About this simple blog</h2>
                <p>
                    Simple Blog is a sleek and modern blogging platform designed to make it easy for users to create and share their thoughts with the world. 
                    It is an ideal platform for both beginners and seasoned bloggers, offering a clean and minimalistic interface that focuses on the content itself.
                     With a simple yet effective design, Simple Blog allows users to publish articles, post images, and share their experiences in a seamless way.
                      Whether you are a passionate writer, a professional content creator, or someone who wants to share personal stories with a wider audience, Simple Blog provides an intuitive space to get started.
                
                       The platform’s responsive design ensures that your blog looks great on all devices, whether viewed on a desktop, tablet, or mobile phone. 
                       One of the key features of Simple Blog is its flexibility. The platform offers a range of customizable templates, enabling you to adjust the look and feel of your blog according to your personal pref
                       erences. 
                </p>                            
            </div>                    
        </div>
    </div>
    <div class="row tm-row tm-mb-120">
        <div class="col-lg-4 tm-about-col">
            <div class="tm-bg-gray tm-about-pad">
                <div class="text-center tm-mt-40 tm-mb-60">
                    <i class="fas fa-bezier-curve fa-4x tm-color-primary"></i>                            
                </div>                        
                <h2 class="mb-3 tm-color-primary tm-post-title">Background</h2>
                <p class="mb-0 tm-line-height-short">
                    Phasellus pulvinar nisl ornare leo porttitor, et vestibulum lorem semper. 
                    Duis risus ex, molestie sit amet magna in,
                    pharetra pellentesque est. Curabitur elit metus.
                </p>
            </div>
        </div>
        <div class="col-lg-4 tm-about-col">
            <div class="tm-bg-gray tm-about-pad">
                <div class="text-center tm-mt-40 tm-mb-60">
                    <i class="fas fa-users-cog fa-4x tm-color-primary"></i>                            
                </div>                        
                <h2 class="mb-3 tm-color-primary tm-post-title">Teamwork</h2>
                <p class="mb-0 tm-line-height-short">
                    Suspendisse ullamcorper, mi vel molestie ornare, arcu magna euismod ipsum, in malesuada nulla magna ut enim. 
                    Morbi lacinia magna sed auctor, vitae nunc cursus.
                </p>
            </div>
        </div>
        <div class="col-lg-4 tm-about-col">
            <div class="tm-bg-gray tm-about-pad">
                <div class="text-center tm-mt-40 tm-mb-60">
                    <i class="fab fa-creative-commons-sampling fa-4x tm-color-primary"></i>                            
                </div>                        
                <h2 class="mb-3 tm-color-primary tm-post-title">Our Core Value</h2>
                <p class="mb-0 tm-line-height-short">
                    Nunc mi ante, suscipit vel dapibus et, volutpat sit amet ante. In tempor nec sem vitae varius. Aliquam tincidunt orci sem, et imperdiet massa consectetur nec.
                </p>
            </div>
        </div>
    </div>            
    <div class="row tm-row tm-mb-60">
        <div class="col-12">
            <hr class="tm-hr-primary  tm-mb-55">
        </div>                
        <div class="col-lg-6 tm-mb-60 tm-person-col">
            <div class="media tm-person">
                <img src="{% static 'img/about-02.jpg' %}" alt="Image" class="img-fluid mr-4">
                <div class="media-body">
                    <h2 class="tm-color-primary tm-post-title mb-2">Samandar Nemataliyev</h2>
                    <h3 class="tm-h3 mb-3">Team Member</h3>
                    <p class="mb-0 tm-line-height-short">
                        Python & Django web developer from Fergana.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 tm-mb-60 tm-person-col">
            <div class="media tm-person">
                <img src="{% static 'img/about-03.jpg' %}" alt="Image" class="img-fluid mr-4">
                <div class="media-body">
                    <h2 class="tm-color-primary tm-post-title mb-2">Shohjahon Nurxanov</h2>
                    <h3 class="tm-h3 mb-3">Team Member</h3>
                    <p class="mb-0 tm-line-height-short">
                        Python & Django web developer from Samarqand.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 tm-mb-60 tm-person-col">
            <div class="media tm-person">
                <img src="{% static 'img/about-05.jpg' %}" alt="Image" class="img-fluid mr-4">
                <div class="media-body">
                    <h2 class="tm-color-primary tm-post-title mb-2">Madinaxon Maxmudova</h2>
                    <h3 class="tm-h3 mb-3">Team Member</h3>
                    <p class="mb-0 tm-line-height-short">
                        Python & Django web developer from Tashkent.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-6 tm-mb-60 tm-person-col">
            <div class="media tm-person">
                <img src="{% static 'img/about-05.jpg' %}" alt="Image" class="img-fluid mr-4">
                <div class="media-body">
                    <h2 class="tm-color-primary tm-post-title mb-2">Nasiba Alisherova</h2>
                    <h3 class="tm-h3 mb-3">Team Member</h3>
                    <p class="mb-0 tm-line-height-short">
                        Python & Django web developer from Tashkent.

                    </p>
                </div>
            </div>
        </div>
    </div>        
{% endblock %}

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
	<title>Simple Blog</title>
	<link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}"> <!-- https://fontawesome.com/ -->
	<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/templatemo-xtra-blog.css' %}" rel="stylesheet">
    <style>
    .post_commentbox {
    display: flex;
    flex-wrap: wrap;
    gap: 20px; /* Adjust space between items */
}

.post_commentbox a,
.post_commentbox span {
    margin-right: 10px; /* Adds some space between elements */
}

.views, .created_at, .categories {
    display: inline-block;
}
</style>

    <style>
        .like-btn {
            background: linear-gradient(45deg, #ff416c, #ff4b2b);
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 18px;
            font-weight: bold;
            border-radius: 8px;
            display: flex;
            align-items: center;
            gap: 10px;
            transition: all 0.3s ease-in-out;
            cursor: pointer;
        }

        .like-btn:hover {
            background: linear-gradient(45deg, #ff4b2b, #ff416c);
            transform: scale(1.05);
        }

        .like-btn i {
            font-size: 20px;
        }
    </style>
</head>
<body>
	<header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>            
                <h1 class="text-center">Simple Blog</h1>
            </div>
            <nav class="tm-nav" id="tm-nav">            
                <ul>
                    <li class="tm-nav-item"><a href="{% url 'blog:index' %}" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Blog Home
                    </a></li>
                    <li class="tm-nav-item"><a href="{% url 'blog:post_create' %}" class="tm-nav-link">
                        <i class="fas fa-file-alt"></i>
                        Add Post
                    </a></li>
                    <li class="tm-nav-item"><a href="{% url 'blog:about' %}" class="tm-nav-link">
                        <i class="fas fa-users"></i>
                        About Simple Blog
                    </a></li>
                    <li class="tm-nav-item"><a href="{% url 'blog:contact' %}" class="tm-nav-link">
                        <i class="far fa-comments"></i>
                        Contact Us
                    </a></li>
                    {% if user.is_authenticated %}
            <!-- Show these when user is logged in -->
            <li class="tm-nav-item"><a href="{% url 'profile' %}" class="tm-nav-link">
                <i class="fas fa-user"></i>
                Profile
            </a></li>
            <li class="tm-nav-item"><a href="{% url 'logout' %}" class="tm-nav-link">
                <i class="fas fa-sign-out-alt"></i>
                Logout
            </a></li>
        {% else %}
            <!-- Show these when user is not logged in -->
            <li class="tm-nav-item"><a href="{% url 'login' %}" class="tm-nav-link">
                <i class="fas fa-sign-in-alt"></i>
                Login
            </a></li>
            <li class="tm-nav-item"><a href="{% url 'signup' %}" class="tm-nav-link">
                <i class="fas fa-user-plus"></i>
                Sign Up
            </a></li>
        {% endif %}
                </ul>
            </nav>
            <div class="tm-mb-65">
                <a rel="nofollow" href="https://fb.com/templatemo" class="tm-social-link">
                    <i class="fab fa-facebook tm-social-icon"></i>
                </a>
                <a href="https://twitter.com" class="tm-social-link">
                    <i class="fab fa-twitter tm-social-icon"></i>
                </a>
                <a href="https://instagram.com" class="tm-social-link">
                    <i class="fab fa-instagram tm-social-icon"></i>
                </a>
                <a href="https://linkedin.com" class="tm-social-link">
                    <i class="fab fa-linkedin tm-social-icon"></i>
                </a>
            </div>
            <p class="tm-mb-80 pr-5 text-white">
                Simple Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.
            </p>
        </div>
    </header>
    <div class="container-fluid">
        <main class="tm-main">
            <!-- Search form -->
            <div class="row tm-row">
                <div class="col-12">
                    <form method="GET" action="{% url 'blog:search' %}" class="form-inline tm-mb-80 tm-search-form">                
                        <input class="form-control tm-search-input" name="query" type="text" id="search" placeholder="Search..." aria-label="Search" value="{{ query }}">
                        <button class="tm-search-button" type="submit">
                            <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                        </button>                                
                    </form>
                </div>                
            </div> 
        {% block main %}
        {% endblock %}
            <footer class="row tm-row">
                <hr class="col-12">
                <div class="col-md-6 col-12 tm-color-gray">
                    Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Copyright {{ today.year }} Simple Blog Company Co. Ltd.
                </div>
            </footer>
        </main>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/templatemo-script.js' %}"></script>
</body>
</html>

templates/blog/category_post.html
{% extends 'blog/base.html' %}

{% block main %}
{% for post in posts %}
    <article class="col-12 col-md-6 tm-post">
        <hr class="tm-hr-primary">
        <a href="{% url 'blog:detail' post.id %}" class="effect-lily tm-post-link tm-pt-60">
            <div class="tm-post-link-inner">
                {% if post.image %}
                {% load static %}
                    <img src="{{ post.image.url }}" alt="Image" class="img-fluid">
                {% else %}
                    <img src="{% static 'img/default.png' %}" alt="Image" class="img-fluid">
                {% endif %}
            </div>
            <span class="position-absolute tm-new-badge">New</span>
            <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ post.title}}</h2>
        </a>                    
        <p class="tm-pt-30">
            {{ post.short_desc|safe }}
        </p>
        <div class="d-flex justify-content-between tm-pt-45">
            <span class="tm-color-primary">
                {% for ctg in post.categories.all %}
                    <a href="{% url 'blog:category_posts' ctg.pk %}" class="tm-color-primary">{{ ctg.name }}</a>
                {% endfor %}
            </span>
            <span class="tm-color-primary">{{ today }}</span>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <span>{{ post.comments.count }} comments</span>
            <span>by {{ post.author.first_name }}</span>
        </div>
    </article>
{% endfor %}
{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% block main %}            
            <div class="row tm-row">

                {% for post in posts %}
                <!-- {{ post }} -->
                <article class="col-12 col-md-6 tm-post">
                    <hr class="tm-hr-primary">
                    <a href="{% url 'blog:detail' post.id %}" class="effect-lily tm-post-link tm-pt-60">
                        <div class="tm-post-link-inner">
                            {% if post.image %}
                            {% load static %}
                                <img src="{{ post.image.url }}" alt="Image" class="img-fluid">
                            {% else %}
                                <img src="{% static 'img/default.png' %}" alt="Image" class="img-fluid">
                            {% endif %}
                        </div>
                        <span class="position-absolute tm-new-badge">New</span>
                        <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ post.title}}</h2>
                    </a>                    
                    <p class="tm-pt-30">
                        {{ post.short_desc|safe }}
                    </p>
                    <div class="d-flex justify-content-between tm-pt-45">
                        <span class="tm-color-primary">
                            {% for ctg in post.categories.all %}
                                <a href="{% url 'blog:category_posts' ctg.pk %}">{{ ctg.name }}</a>  
                            {% endfor %}
                        </span>
                        <span class="tm-color-primary">{{ today }}</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <span>{{ post.comments.count }} comments</span>
                        <span>by {{ post.author.first_name }}</span>
                    </div>
                </article>
                {% endfor %}
            </div>
            <div class="row tm-row tm-mt-100 tm-mb-75">
                <div class="tm-prev-next-wrapper">
                    {% if posts.has_previous %}
                        <a href="?page={{ posts.previous_page_number }}" class="mb-2 tm-btn tm-btn-primary tm-prev-next tm-mr-20">Prev</a>
                    {% else %}
                        <span class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Prev</span>
                    {% endif %}
                    
                    {% if posts.has_next %}
                        <a href="?page={{ posts.next_page_number }}" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
                    {% else %}
                        <span class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled">Next</span>
                    {% endif %}
                </div>
            
                <div class="tm-paging-wrapper">
                    <span class="d-inline-block mr-3">Page</span>
                    <nav class="tm-paging-nav d-inline-block">
                        <ul>
                            {% for num in posts.paginator.page_range %}
                                <li class="tm-paging-item {% if posts.number == num %}active{% endif %}">
                                    <a href="?page={{ num }}" class="mb-2 tm-btn tm-paging-link">{{ num }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
            </div>
{% endblock %}

templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% block title %} Yangi Post Qo'shish {% endblock %}

{% block main %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg rounded">
                <div class="card-header bg-success text-white text-center">
                    <h3>Yangi Post Qo'shish</h3>
                </div>
                <div class="card-body">
                    <form method="POST" action="{% url 'blog:post_create' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.media }}
                        {% for field in form %}
                        <div class="mb-3">
                            <label class="form-label fw-bold">{{ field.label }}</label>
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                        {% endfor %}
                        
                        <!-- Submit va Bekor qilish tugmalari -->
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary px-4 py-2">Qo'shish</button>
                            <a href="{% url 'blog:index' %}" class="btn btn-secondary px-4 py-2">Bekor qilish</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/post_delete.html
{% extends "blog/base.html" %}

{% block main %}
    <h2>Ushbu postni o‘chirishni xohlaysizmi?</h2>
    <p><strong>{{ post.title }}</strong> ni o‘chirmoqchimisiz?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Ha, o‘chirish</button>
        <a href="{% url 'blog:detail' post.pk %}" class="btn btn-secondary">Bekor qilish</a>
    </form>
{% endblock %}